//! Generic input conversion infrastructure.
//!
//! Converters are intentionally modeled as external tools. That keeps `hyperdrc`
//! focused on readiness checks while allowing format bridges such as TransJLC to
//! be added without entangling their file naming logic with the checker.

use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{Context, Result, anyhow};

use crate::cli::{ConversionBackend, SourceEda};
use crate::process_lifecycle::{ChildProcessGuard, configure_child_command};

#[derive(Clone, Debug)]
/// Public data model for `ConversionRequest`.
pub struct ConversionRequest {
    /// Field `backend`.
    pub backend: ConversionBackend,
    /// Field `input_dir`.
    pub input_dir: PathBuf,
    /// Field `output_dir`.
    pub output_dir: PathBuf,
    /// Field `source_eda`.
    pub source_eda: SourceEda,
    /// Field `zip`.
    pub zip: bool,
    /// Field `zip_name`.
    pub zip_name: String,
    /// Field `top_color_image`.
    pub top_color_image: Option<PathBuf>,
    /// Field `bottom_color_image`.
    pub bottom_color_image: Option<PathBuf>,
    /// Field `transjlc_bin`.
    pub transjlc_bin: PathBuf,
    /// Field `kicad_cli_bin`.
    pub kicad_cli_bin: PathBuf,
    /// Field `extra_args`.
    pub extra_args: Vec<String>,
    /// Field `kicad_drill_args`.
    pub kicad_drill_args: Vec<String>,
    /// Field `kicad_pos_args`.
    pub kicad_pos_args: Vec<String>,
    /// Field `kicad_ipcd356_args`.
    pub kicad_ipcd356_args: Vec<String>,
    /// Field `kicad_drc_args`.
    pub kicad_drc_args: Vec<String>,
    /// Field `kicad_handoff_exports`.
    pub kicad_handoff_exports: bool,
    /// Field `kicad_review_exports`.
    pub kicad_review_exports: bool,
    /// Field `kicad_dxf_args`.
    pub kicad_dxf_args: Vec<String>,
    /// Field `kicad_svg_args`.
    pub kicad_svg_args: Vec<String>,
    /// Field `kicad_pdf_args`.
    pub kicad_pdf_args: Vec<String>,
}

/// Run or compute `convert`.
pub fn convert(request: &ConversionRequest) -> Result<ConversionOutput> {
    match request.backend {
        ConversionBackend::Transjlc => TransjlcConverter.convert(request),
        ConversionBackend::KicadCli => KicadCliConverter.convert(request),
    }
}

#[derive(Clone, Debug)]
/// Public data model for `ConversionOutput`.
pub struct ConversionOutput {
    /// Field `source_dir`.
    pub source_dir: PathBuf,
    /// Field `gerber_dir`.
    pub gerber_dir: PathBuf,
    /// Optional KiCad DRC JSON report generated by the converter.
    pub drc_report: Option<PathBuf>,
    /// Deterministic hash over the converter input file/tree.
    pub input_hash: String,
    /// Captured external tool steps that produced this conversion.
    pub steps: Vec<ConversionStepLog>,
    /// Captured converter version probe when the executable could be run.
    pub version: Option<ConversionStepLog>,
    /// Sorted files present in the conversion output directory after execution.
    pub output_manifest: Vec<ConversionManifestEntry>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Captured evidence for one external conversion command.
pub struct ConversionStepLog {
    /// Human-readable operation label.
    pub operation: String,
    /// Rendered command line.
    pub command: String,
    /// Process exit status as reported by the OS.
    pub status: String,
    /// Captured standard output, truncated to a bounded diagnostic payload.
    pub stdout: String,
    /// Captured standard error, truncated to a bounded diagnostic payload.
    pub stderr: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// One generated output file recorded in a converter manifest.
pub struct ConversionManifestEntry {
    /// Path relative to the conversion output directory.
    pub path: String,
    /// File size in bytes.
    pub bytes: u64,
}

trait Converter {
    fn convert(&self, request: &ConversionRequest) -> Result<ConversionOutput>;
}

struct TransjlcConverter;
struct KicadCliConverter;

impl Converter for TransjlcConverter {
    fn convert(&self, request: &ConversionRequest) -> Result<ConversionOutput> {
        std::fs::create_dir_all(&request.output_dir)
            .with_context(|| format!("failed to create {}", request.output_dir.display()))?;

        let step = run_conversion_command(
            transjlc_command(request),
            "TransJLC conversion",
            &request.transjlc_bin,
            "failed while waiting for TransJLC conversion to finish",
        )?;

        if !step_success(&step) {
            return Err(anyhow!(
                "TransJLC conversion failed for {} with status {}",
                request.input_dir.display(),
                step.status
            ));
        }

        Ok(ConversionOutput {
            source_dir: request.input_dir.clone(),
            gerber_dir: request.output_dir.clone(),
            drc_report: None,
            input_hash: input_hash(&request.input_dir)?,
            version: Some(probe_converter_version(&request.transjlc_bin)?),
            steps: vec![step],
            output_manifest: output_manifest(&request.output_dir)?,
        })
    }
}

impl Converter for KicadCliConverter {
    fn convert(&self, request: &ConversionRequest) -> Result<ConversionOutput> {
        std::fs::create_dir_all(&request.output_dir)
            .with_context(|| format!("failed to create {}", request.output_dir.display()))?;

        let mut steps = Vec::new();
        steps.push(run_kicad_cli_command(
            kicad_cli_gerber_command(request),
            request,
            "Gerber export",
            "failed while waiting for KiCad CLI Gerber export to finish",
        )?);
        steps.push(run_kicad_cli_command(
            kicad_cli_drill_command(request),
            request,
            "drill export",
            "failed while waiting for KiCad CLI drill export to finish",
        )?);
        steps.push(run_kicad_cli_command(
            kicad_cli_position_command(request),
            request,
            "position export",
            "failed while waiting for KiCad CLI position export to finish",
        )?);
        steps.push(run_kicad_cli_command(
            kicad_cli_ipcd356_command(request),
            request,
            "IPC-D-356 export",
            "failed while waiting for KiCad CLI IPC-D-356 export to finish",
        )?);
        steps.push(run_kicad_cli_command(
            kicad_cli_drc_command(request),
            request,
            "DRC report",
            "failed while waiting for KiCad CLI DRC report to finish",
        )?);
        if request.kicad_handoff_exports {
            for (operation, command) in kicad_cli_handoff_commands(request) {
                steps.push(run_kicad_cli_command(
                    command,
                    request,
                    operation,
                    "failed while waiting for KiCad CLI handoff export to finish",
                )?);
            }
        }
        if request.kicad_review_exports {
            steps.push(run_kicad_cli_command(
                kicad_cli_dxf_command(request),
                request,
                "DXF export",
                "failed while waiting for KiCad CLI DXF export to finish",
            )?);
            steps.push(run_kicad_cli_command(
                kicad_cli_svg_command(request),
                request,
                "SVG export",
                "failed while waiting for KiCad CLI SVG export to finish",
            )?);
            steps.push(run_kicad_cli_command(
                kicad_cli_pdf_command(request),
                request,
                "PDF export",
                "failed while waiting for KiCad CLI PDF export to finish",
            )?);
        }

        Ok(ConversionOutput {
            source_dir: request.input_dir.clone(),
            gerber_dir: request.output_dir.clone(),
            drc_report: Some(kicad_drc_report_path(request)),
            input_hash: input_hash(&request.input_dir)?,
            version: Some(probe_converter_version(&request.kicad_cli_bin)?),
            steps,
            output_manifest: output_manifest(&request.output_dir)?,
        })
    }
}

fn probe_converter_version(executable: &Path) -> Result<ConversionStepLog> {
    let mut command = Command::new(executable);
    command.arg("--version");
    run_conversion_command(
        command,
        "version probe",
        executable,
        "failed while waiting for converter version probe to finish",
    )
}

fn run_conversion_command(
    mut command: Command,
    operation: &str,
    executable: &Path,
    wait_context: &'static str,
) -> Result<ConversionStepLog> {
    let rendered_command = render_command(&command);
    configure_child_command(&mut command);
    command.stdout(Stdio::piped()).stderr(Stdio::piped());
    let child = command.spawn().with_context(|| {
        format!(
            "failed to run converter executable {}",
            executable.display()
        )
    })?;
    let output = ChildProcessGuard::new(child)
        .wait_with_output()
        .with_context(|| wait_context)?;

    Ok(ConversionStepLog {
        operation: operation.to_string(),
        command: rendered_command,
        status: output.status.to_string(),
        stdout: bounded_output(&output.stdout),
        stderr: bounded_output(&output.stderr),
    })
}

fn step_success(step: &ConversionStepLog) -> bool {
    step.status.starts_with("exit status: 0") || step.status == "exit code: 0"
}

fn render_command(command: &Command) -> String {
    std::iter::once(command.get_program())
        .chain(command.get_args())
        .map(|part| shellish_quote(&part.to_string_lossy()))
        .collect::<Vec<_>>()
        .join(" ")
}

fn shellish_quote(value: &str) -> String {
    if value
        .chars()
        .all(|character| character.is_ascii_alphanumeric() || "-_./:=+".contains(character))
    {
        value.to_string()
    } else {
        format!("'{}'", value.replace('\'', "'\\''"))
    }
}

fn bounded_output(bytes: &[u8]) -> String {
    const LIMIT: usize = 4096;
    let mut text = String::from_utf8_lossy(&bytes[..bytes.len().min(LIMIT)]).into_owned();
    if bytes.len() > LIMIT {
        text.push_str("\n[truncated]");
    }
    text
}

fn input_hash(path: &Path) -> Result<String> {
    let mut entries = Vec::new();
    collect_existing_files(path, path, &mut entries)?;
    let mut hasher = DefaultHasher::new();
    for entry in entries {
        entry.relative.hash(&mut hasher);
        entry.bytes.hash(&mut hasher);
        let content = std::fs::read(&entry.absolute).with_context(|| {
            format!(
                "failed to read converter input {}",
                entry.absolute.display()
            )
        })?;
        content.hash(&mut hasher);
    }
    Ok(format!("hyperdrc-input-v1:{:016x}", hasher.finish()))
}

fn output_manifest(path: &Path) -> Result<Vec<ConversionManifestEntry>> {
    let mut files = Vec::new();
    if path.exists() {
        collect_existing_files(path, path, &mut files)?;
    }
    Ok(files
        .into_iter()
        .map(|file| ConversionManifestEntry {
            path: file.relative,
            bytes: file.bytes,
        })
        .collect())
}

#[derive(Debug)]
struct FileEvidence {
    absolute: PathBuf,
    relative: String,
    bytes: u64,
}

fn collect_existing_files(root: &Path, path: &Path, files: &mut Vec<FileEvidence>) -> Result<()> {
    if path.is_file() {
        let metadata = std::fs::metadata(path)
            .with_context(|| format!("failed to read metadata for {}", path.display()))?;
        files.push(FileEvidence {
            absolute: path.to_path_buf(),
            relative: relative_path(root, path),
            bytes: metadata.len(),
        });
        files.sort_by(|left, right| left.relative.cmp(&right.relative));
        return Ok(());
    }
    if path.is_dir() {
        let mut children = std::fs::read_dir(path)
            .with_context(|| format!("failed to scan directory {}", path.display()))?
            .collect::<std::io::Result<Vec<_>>>()
            .with_context(|| format!("failed to scan directory {}", path.display()))?;
        children.sort_by_key(|entry| entry.path());
        for child in children {
            collect_existing_files(root, &child.path(), files)?;
        }
    }
    Ok(())
}

fn relative_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .ok()
        .filter(|relative| !relative.as_os_str().is_empty())
        .unwrap_or(path)
        .display()
        .to_string()
}

fn transjlc_command(request: &ConversionRequest) -> Command {
    let mut command = Command::new(&request.transjlc_bin);
    command
        .arg("--path")
        .arg(&request.input_dir)
        .arg("--output_path")
        .arg(&request.output_dir)
        .arg("--eda")
        .arg(request.source_eda.as_transjlc_arg())
        .arg("--zip")
        .arg(if request.zip { "true" } else { "false" })
        .arg("--zip_name")
        .arg(&request.zip_name);

    if let Some(path) = &request.top_color_image {
        command.arg("--top_color_image").arg(path);
    }
    if let Some(path) = &request.bottom_color_image {
        command.arg("--bottom_color_image").arg(path);
    }
    for arg in &request.extra_args {
        command.arg(arg);
    }

    command
}

fn run_kicad_cli_command(
    command: Command,
    request: &ConversionRequest,
    operation: &str,
    wait_context: &'static str,
) -> Result<ConversionStepLog> {
    let step = run_conversion_command(command, operation, &request.kicad_cli_bin, wait_context)?;

    if !step_success(&step) && !(operation == "DRC report" && step.status.ends_with("5")) {
        return Err(anyhow!(
            "KiCad CLI {operation} failed for {} with status {}",
            request.input_dir.display(),
            step.status
        ));
    }

    Ok(step)
}

fn kicad_cli_gerber_command(request: &ConversionRequest) -> Command {
    let mut command = Command::new(&request.kicad_cli_bin);
    command
        .arg("pcb")
        .arg("export")
        .arg("gerbers")
        .arg("--output")
        .arg(&request.output_dir);

    for arg in &request.extra_args {
        command.arg(arg);
    }

    command.arg(&request.input_dir);
    command
}

fn kicad_cli_drill_command(request: &ConversionRequest) -> Command {
    let mut command = Command::new(&request.kicad_cli_bin);
    command
        .arg("pcb")
        .arg("export")
        .arg("drill")
        .arg("--output")
        .arg(&request.output_dir)
        .arg("--format")
        .arg("excellon");

    for arg in &request.kicad_drill_args {
        command.arg(arg);
    }

    command.arg(&request.input_dir);
    command
}

fn kicad_cli_position_command(request: &ConversionRequest) -> Command {
    let mut command = Command::new(&request.kicad_cli_bin);
    command
        .arg("pcb")
        .arg("export")
        .arg("pos")
        .arg("--output")
        .arg(request.output_dir.join("positions.pos"))
        .arg("--format")
        .arg("csv")
        .arg("--units")
        .arg("mm");

    for arg in &request.kicad_pos_args {
        command.arg(arg);
    }

    command.arg(&request.input_dir);
    command
}

fn kicad_cli_ipcd356_command(request: &ConversionRequest) -> Command {
    let mut command = Command::new(&request.kicad_cli_bin);
    command
        .arg("pcb")
        .arg("export")
        .arg("ipcd356")
        .arg("--output")
        .arg(request.output_dir.join("ipc356.d356"));

    for arg in &request.kicad_ipcd356_args {
        command.arg(arg);
    }

    command.arg(&request.input_dir);
    command
}

fn kicad_cli_drc_command(request: &ConversionRequest) -> Command {
    let mut command = Command::new(&request.kicad_cli_bin);
    command
        .arg("pcb")
        .arg("drc")
        .arg("--output")
        .arg(kicad_drc_report_path(request))
        .arg("--format")
        .arg("json")
        .arg("--units")
        .arg("mm")
        .arg("--severity-all");

    for arg in &request.kicad_drc_args {
        command.arg(arg);
    }

    command.arg(&request.input_dir);
    command
}

fn kicad_drc_report_path(request: &ConversionRequest) -> PathBuf {
    request.output_dir.join("kicad_drc.json")
}

fn kicad_cli_dxf_command(request: &ConversionRequest) -> Command {
    let mut command = Command::new(&request.kicad_cli_bin);
    command
        .arg("pcb")
        .arg("export")
        .arg("dxf")
        .arg("--output")
        .arg(request.output_dir.join("fab_drawing.dxf"));

    for arg in &request.kicad_dxf_args {
        command.arg(arg);
    }

    command.arg(&request.input_dir);
    command
}

fn kicad_cli_svg_command(request: &ConversionRequest) -> Command {
    let mut command = Command::new(&request.kicad_cli_bin);
    command
        .arg("pcb")
        .arg("export")
        .arg("svg")
        .arg("--output")
        .arg(request.output_dir.join("assembly_drawing.svg"))
        .arg("--mode-single");

    for arg in &request.kicad_svg_args {
        command.arg(arg);
    }

    command.arg(&request.input_dir);
    command
}

fn kicad_cli_pdf_command(request: &ConversionRequest) -> Command {
    let mut command = Command::new(&request.kicad_cli_bin);
    command
        .arg("pcb")
        .arg("export")
        .arg("pdf")
        .arg("--output")
        .arg(request.output_dir.join("fab_drawing.pdf"))
        .arg("--mode-single");

    for arg in &request.kicad_pdf_args {
        command.arg(arg);
    }

    command.arg(&request.input_dir);
    command
}

fn kicad_cli_handoff_commands(request: &ConversionRequest) -> Vec<(&'static str, Command)> {
    vec![
        (
            "IPC-2581 export",
            kicad_cli_export_command(request, "ipc2581", "ipc2581.xml", &[]),
        ),
        (
            "ODB++ export",
            kicad_cli_export_command(request, "odb", "odb_output.zip", &[]),
        ),
        (
            "STEP export",
            kicad_cli_export_command(request, "step", "board.step", &[]),
        ),
        (
            "GLB export",
            kicad_cli_export_command(request, "glb", "board.glb", &[]),
        ),
        (
            "PLY export",
            kicad_cli_export_command(request, "ply", "board.ply", &[]),
        ),
        (
            "statistics export",
            kicad_cli_export_command(request, "stats", "statistics.json", &["--format", "json"]),
        ),
    ]
}

fn kicad_cli_export_command(
    request: &ConversionRequest,
    export: &str,
    output_name: &str,
    extra_args: &[&str],
) -> Command {
    let mut command = Command::new(&request.kicad_cli_bin);
    command
        .arg("pcb")
        .arg("export")
        .arg(export)
        .arg("--output")
        .arg(request.output_dir.join(output_name));

    for arg in extra_args {
        command.arg(arg);
    }

    command.arg(&request.input_dir);
    command
}

/// Run or compute `default_conversion_output_dir`.
pub fn default_conversion_output_dir(base: &Path, index: usize) -> PathBuf {
    base.join(format!("conversion-{index}"))
}

#[cfg(test)]
mod tests {
    use std::fs::remove_dir_all;
    use std::path::PathBuf;
    use std::process;

    use super::{ConversionOutput, ConversionRequest, default_conversion_output_dir};
    use crate::cli::{ConversionBackend, SourceEda};

    #[test]
    fn default_conversion_output_dir_is_stable_and_separate_per_input() {
        assert_eq!(
            default_conversion_output_dir(&PathBuf::from("out"), 2),
            PathBuf::from("out/conversion-2")
        );
    }

    #[test]
    fn conversion_output_points_at_generated_gerber_directory() {
        let output = ConversionOutput {
            source_dir: PathBuf::from("source"),
            gerber_dir: PathBuf::from("converted"),
            drc_report: Some(PathBuf::from("converted/kicad_drc.json")),
            input_hash: "hyperdrc-input-v1:test".to_string(),
            steps: Vec::new(),
            version: None,
            output_manifest: Vec::new(),
        };

        assert_eq!(output.source_dir, PathBuf::from("source"));
        assert_eq!(output.gerber_dir, PathBuf::from("converted"));
        assert_eq!(
            output.drc_report,
            Some(PathBuf::from("converted/kicad_drc.json"))
        );
        assert_eq!(output.input_hash, "hyperdrc-input-v1:test");
    }

    #[test]
    fn converter_provenance_hashes_inputs_and_manifests_outputs() {
        let process_id = process::id();
        let temp_input = PathBuf::from(format!("/tmp/hyperdrc-provenance-input-{process_id}"));
        let temp_output = PathBuf::from(format!("/tmp/hyperdrc-provenance-output-{process_id}"));
        let _ = remove_dir_all(&temp_input);
        let _ = remove_dir_all(&temp_output);
        std::fs::create_dir_all(temp_input.join("nested")).unwrap();
        std::fs::create_dir_all(&temp_output).unwrap();
        std::fs::write(temp_input.join("board.kicad_pcb"), "(kicad_pcb)").unwrap();
        std::fs::write(temp_input.join("nested/readme.txt"), "handoff").unwrap();
        std::fs::write(temp_output.join("top.gbr"), "G04 top*").unwrap();
        std::fs::write(temp_output.join("drill.drl"), "M48").unwrap();

        let first_hash = super::input_hash(&temp_input).unwrap();
        let second_hash = super::input_hash(&temp_input).unwrap();
        let manifest = super::output_manifest(&temp_output).unwrap();

        assert!(first_hash.starts_with("hyperdrc-input-v1:"));
        assert_eq!(first_hash, second_hash);
        assert_eq!(manifest.len(), 2);
        assert_eq!(manifest[0].path, "drill.drl");
        assert_eq!(manifest[0].bytes, 3);
        assert_eq!(manifest[1].path, "top.gbr");

        let _ = remove_dir_all(&temp_input);
        let _ = remove_dir_all(&temp_output);
    }

    #[test]
    fn transjlc_request_keeps_backend_specific_options_together() {
        let request = ConversionRequest {
            backend: ConversionBackend::Transjlc,
            input_dir: PathBuf::from("in"),
            output_dir: PathBuf::from("out"),
            source_eda: SourceEda::Kicad,
            zip: true,
            zip_name: "board".to_string(),
            top_color_image: Some(PathBuf::from("top.png")),
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("TransJLC"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: vec!["--foo".to_string(), "--bar=baz".to_string()],
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        assert_eq!(request.source_eda.as_transjlc_arg(), "kicad");
        assert!(request.zip);
    }

    #[test]
    fn transjlc_command_includes_extra_backend_args() {
        let request = ConversionRequest {
            backend: ConversionBackend::Transjlc,
            input_dir: PathBuf::from("in"),
            output_dir: PathBuf::from("out"),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "board".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("transjlc"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: vec!["--foo".to_string(), "--bar=baz".to_string()],
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let command = super::transjlc_command(&request);

        let rendered = format!("{:?}", command);
        assert!(rendered.contains("--foo"));
        assert!(rendered.contains("--bar=baz"));
    }

    #[test]
    fn transjlc_command_includes_color_images_when_supplied() {
        let request = ConversionRequest {
            backend: ConversionBackend::Transjlc,
            input_dir: PathBuf::from("in"),
            output_dir: PathBuf::from("out"),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "board".to_string(),
            top_color_image: Some(PathBuf::from("top-art.png")),
            bottom_color_image: Some(PathBuf::from("bottom-art.png")),
            transjlc_bin: PathBuf::from("transjlc"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let command = super::transjlc_command(&request);
        let rendered = format!("{:?}", command);

        assert!(rendered.contains("--top_color_image"));
        assert!(rendered.contains("top-art.png"));
        assert!(rendered.contains("--bottom_color_image"));
        assert!(rendered.contains("bottom-art.png"));
    }

    #[test]
    fn kicad_cli_command_exports_gerbers_to_output_dir() {
        let request = ConversionRequest {
            backend: ConversionBackend::KicadCli,
            input_dir: PathBuf::from("board.kicad_pcb"),
            output_dir: PathBuf::from("gerbers"),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("TransJLC"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: vec!["--layers".to_string(), "F.Cu,B.Cu".to_string()],
            kicad_drill_args: vec!["--generate-map".to_string()],
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let command = super::kicad_cli_gerber_command(&request);
        let rendered = format!("{:?}", command);

        assert!(rendered.contains("kicad-cli"));
        assert!(rendered.contains("pcb"));
        assert!(rendered.contains("export"));
        assert!(rendered.contains("gerbers"));
        assert!(rendered.contains("--output"));
        assert!(rendered.contains("gerbers"));
        assert!(rendered.contains("--layers"));
        assert!(rendered.contains("F.Cu,B.Cu"));
        assert!(rendered.contains("board.kicad_pcb"));
    }

    #[test]
    fn kicad_cli_drill_command_exports_excellon_to_output_dir() {
        let request = ConversionRequest {
            backend: ConversionBackend::KicadCli,
            input_dir: PathBuf::from("board.kicad_pcb"),
            output_dir: PathBuf::from("drills"),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("TransJLC"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: vec!["--generate-map".to_string()],
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let command = super::kicad_cli_drill_command(&request);
        let rendered = format!("{:?}", command);

        assert!(rendered.contains("pcb"));
        assert!(rendered.contains("export"));
        assert!(rendered.contains("drill"));
        assert!(rendered.contains("--output"));
        assert!(rendered.contains("drills"));
        assert!(rendered.contains("--format"));
        assert!(rendered.contains("excellon"));
        assert!(rendered.contains("--generate-map"));
        assert!(rendered.contains("board.kicad_pcb"));
    }

    #[test]
    fn kicad_cli_position_command_exports_csv_centroid_to_output_dir() {
        let request = ConversionRequest {
            backend: ConversionBackend::KicadCli,
            input_dir: PathBuf::from("board.kicad_pcb"),
            output_dir: PathBuf::from("converted"),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("TransJLC"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: Vec::new(),
            kicad_pos_args: vec!["--side".to_string(), "front".to_string()],
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let command = super::kicad_cli_position_command(&request);
        let rendered = format!("{:?}", command);

        assert!(rendered.contains("pcb"));
        assert!(rendered.contains("export"));
        assert!(rendered.contains("pos"));
        assert!(rendered.contains("--output"));
        assert!(rendered.contains("positions.pos"));
        assert!(rendered.contains("--format"));
        assert!(rendered.contains("csv"));
        assert!(rendered.contains("--units"));
        assert!(rendered.contains("mm"));
        assert!(rendered.contains("--side"));
        assert!(rendered.contains("front"));
        assert!(rendered.contains("board.kicad_pcb"));
    }

    #[test]
    fn kicad_cli_ipcd356_command_exports_test_netlist_to_output_dir() {
        let request = ConversionRequest {
            backend: ConversionBackend::KicadCli,
            input_dir: PathBuf::from("board.kicad_pcb"),
            output_dir: PathBuf::from("converted"),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("TransJLC"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: vec!["--custom-flag".to_string()],
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let command = super::kicad_cli_ipcd356_command(&request);
        let rendered = format!("{:?}", command);

        assert!(rendered.contains("pcb"));
        assert!(rendered.contains("export"));
        assert!(rendered.contains("ipcd356"));
        assert!(rendered.contains("--output"));
        assert!(rendered.contains("ipc356.d356"));
        assert!(rendered.contains("--custom-flag"));
        assert!(rendered.contains("board.kicad_pcb"));
    }

    #[test]
    fn kicad_cli_drc_command_exports_json_report_to_output_dir() {
        let request = ConversionRequest {
            backend: ConversionBackend::KicadCli,
            input_dir: PathBuf::from("board.kicad_pcb"),
            output_dir: PathBuf::from("converted"),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("TransJLC"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: vec!["--schematic-parity".to_string()],
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let command = super::kicad_cli_drc_command(&request);
        let rendered = format!("{command:?}");

        assert!(rendered.contains("pcb"));
        assert!(rendered.contains("drc"));
        assert!(rendered.contains("kicad_drc.json"));
        assert!(rendered.contains("--format"));
        assert!(rendered.contains("json"));
        assert!(rendered.contains("--units"));
        assert!(rendered.contains("mm"));
        assert!(rendered.contains("--severity-all"));
        assert!(rendered.contains("--schematic-parity"));
        assert!(rendered.contains("board.kicad_pcb"));
    }

    #[test]
    fn kicad_cli_review_commands_export_named_drawing_sidecars() {
        let request = ConversionRequest {
            backend: ConversionBackend::KicadCli,
            input_dir: PathBuf::from("board.kicad_pcb"),
            output_dir: PathBuf::from("converted"),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("TransJLC"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: true,
            kicad_dxf_args: vec!["--layers".to_string(), "Edge.Cuts".to_string()],
            kicad_svg_args: vec!["--black-and-white".to_string()],
            kicad_pdf_args: vec!["--include-border-title".to_string()],
        };

        let dxf = format!("{:?}", super::kicad_cli_dxf_command(&request));
        assert!(dxf.contains("dxf"));
        assert!(dxf.contains("fab_drawing.dxf"));
        assert!(dxf.contains("--layers"));
        assert!(dxf.contains("Edge.Cuts"));

        let svg = format!("{:?}", super::kicad_cli_svg_command(&request));
        assert!(svg.contains("svg"));
        assert!(svg.contains("assembly_drawing.svg"));
        assert!(svg.contains("--mode-single"));
        assert!(svg.contains("--black-and-white"));

        let pdf = format!("{:?}", super::kicad_cli_pdf_command(&request));
        assert!(pdf.contains("pdf"));
        assert!(pdf.contains("fab_drawing.pdf"));
        assert!(pdf.contains("--mode-single"));
        assert!(pdf.contains("--include-border-title"));
    }

    #[test]
    fn kicad_cli_handoff_commands_export_package_and_mechanical_files() {
        let request = ConversionRequest {
            backend: ConversionBackend::KicadCli,
            input_dir: PathBuf::from("board.kicad_pcb"),
            output_dir: PathBuf::from("converted"),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("TransJLC"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: true,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let rendered = super::kicad_cli_handoff_commands(&request)
            .into_iter()
            .map(|(_, command)| format!("{command:?}"))
            .collect::<Vec<_>>()
            .join("\n");

        assert!(rendered.contains("ipc2581"));
        assert!(rendered.contains("ipc2581.xml"));
        assert!(rendered.contains("odb"));
        assert!(rendered.contains("odb_output.zip"));
        assert!(rendered.contains("step"));
        assert!(rendered.contains("board.step"));
        assert!(rendered.contains("glb"));
        assert!(rendered.contains("board.glb"));
        assert!(rendered.contains("ply"));
        assert!(rendered.contains("board.ply"));
        assert!(rendered.contains("stats"));
        assert!(rendered.contains("statistics.json"));
        assert!(rendered.contains("--format"));
        assert!(rendered.contains("json"));
    }

    #[test]
    fn convert_executes_successful_converter_and_returns_output_paths() {
        let process_id = process::id();
        let temp_input = PathBuf::from(format!("/tmp/hyperdrc-conv-input-{process_id}"));
        let temp_output = PathBuf::from(format!("/tmp/hyperdrc-conv-output-{process_id}"));
        let _ = remove_dir_all(&temp_input);
        let _ = remove_dir_all(&temp_output);
        std::fs::create_dir_all(&temp_input).unwrap();

        let request = ConversionRequest {
            backend: ConversionBackend::Transjlc,
            input_dir: temp_input.clone(),
            output_dir: temp_output.clone(),
            source_eda: SourceEda::Kicad,
            zip: true,
            zip_name: "bundle".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("/bin/true"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: vec!["--noop".to_string()],
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let converted = super::convert(&request).unwrap();

        assert_eq!(converted.source_dir, temp_input);
        assert_eq!(converted.gerber_dir, temp_output);
        assert!(temp_output.exists());
        assert!(converted.input_hash.starts_with("hyperdrc-input-v1:"));
        assert_eq!(
            converted
                .version
                .as_ref()
                .map(|step| step.operation.as_str()),
            Some("version probe")
        );
        assert_eq!(converted.steps.len(), 1);
        assert_eq!(converted.steps[0].operation, "TransJLC conversion");
        assert!(converted.steps[0].command.contains("/bin/true"));
        let _ = remove_dir_all(&temp_input);
        let _ = remove_dir_all(&temp_output);
    }

    #[test]
    fn convert_executes_successful_kicad_cli_converter_and_returns_output_paths() {
        let process_id = process::id();
        let temp_input = PathBuf::from(format!("/tmp/hyperdrc-kicad-input-{process_id}.kicad_pcb"));
        let temp_output = PathBuf::from(format!("/tmp/hyperdrc-kicad-output-{process_id}"));
        let _ = std::fs::remove_file(&temp_input);
        let _ = remove_dir_all(&temp_output);
        std::fs::write(&temp_input, "(kicad_pcb)").unwrap();

        let request = ConversionRequest {
            backend: ConversionBackend::KicadCli,
            input_dir: temp_input.clone(),
            output_dir: temp_output.clone(),
            source_eda: SourceEda::Kicad,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("TransJLC"),
            kicad_cli_bin: PathBuf::from("/bin/true"),
            extra_args: vec!["--noop".to_string()],
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let converted = super::convert(&request).unwrap();

        assert_eq!(converted.source_dir, temp_input);
        assert_eq!(converted.gerber_dir, temp_output);
        assert!(converted.gerber_dir.exists());
        assert!(converted.input_hash.starts_with("hyperdrc-input-v1:"));
        assert_eq!(
            converted
                .version
                .as_ref()
                .map(|step| step.operation.as_str()),
            Some("version probe")
        );
        assert_eq!(converted.steps.len(), 5);
        assert!(converted.steps[0].command.contains("pcb export gerbers"));
        let _ = std::fs::remove_file(converted.source_dir);
        let _ = remove_dir_all(converted.gerber_dir);
    }

    #[test]
    fn convert_reports_command_failure_as_contextual_error() {
        let request = ConversionRequest {
            backend: ConversionBackend::Transjlc,
            input_dir: PathBuf::from("input"),
            output_dir: PathBuf::from("out"),
            source_eda: SourceEda::Auto,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("/bin/false"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let error = super::convert(&request)
            .expect_err("conversion should fail when command returns non-zero");
        let message = format!("{}", error);

        assert!(message.contains("TransJLC conversion failed"));
        assert!(message.contains("input"));
    }

    #[test]
    fn convert_reports_missing_converter_binary() {
        let request = ConversionRequest {
            backend: ConversionBackend::Transjlc,
            input_dir: PathBuf::from("input"),
            output_dir: PathBuf::from("out"),
            source_eda: SourceEda::Auto,
            zip: false,
            zip_name: "Gerber".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("/does-not-exist"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let error = super::convert(&request)
            .expect_err("missing converter should return an execution error");
        let message = format!("{}", error);

        assert!(message.contains("failed to run converter executable"));
        assert!(message.contains("/does-not-exist"));
    }

    #[test]
    fn convert_reports_directory_creation_failure() {
        let process_id = process::id();
        let temp_input = PathBuf::from(format!("/tmp/hyperdrc-conv-input-{process_id}"));
        let temp_output_file = PathBuf::from(format!("/tmp/hyperdrc-output-file-{process_id}.txt"));
        let _ = remove_dir_all(&temp_input);
        std::fs::create_dir_all(&temp_input).unwrap();
        std::fs::write(&temp_output_file, "file-path-conflict").unwrap();

        let request = ConversionRequest {
            backend: ConversionBackend::Transjlc,
            input_dir: temp_input.clone(),
            output_dir: temp_output_file,
            source_eda: SourceEda::Kicad,
            zip: true,
            zip_name: "bundle".to_string(),
            top_color_image: None,
            bottom_color_image: None,
            transjlc_bin: PathBuf::from("/bin/true"),
            kicad_cli_bin: PathBuf::from("kicad-cli"),
            extra_args: Vec::new(),
            kicad_drill_args: Vec::new(),
            kicad_pos_args: Vec::new(),
            kicad_ipcd356_args: Vec::new(),
            kicad_drc_args: Vec::new(),
            kicad_handoff_exports: false,
            kicad_review_exports: false,
            kicad_dxf_args: Vec::new(),
            kicad_svg_args: Vec::new(),
            kicad_pdf_args: Vec::new(),
        };

        let error =
            super::convert(&request).expect_err("directory creation must fail for file path");
        let message = format!("{error}");

        assert!(message.contains("failed to create"));
        let _ = remove_dir_all(&temp_input);
        let _ = std::fs::remove_file(format!("/tmp/hyperdrc-output-file-{process_id}.txt"));
    }
}
