//! KiCad custom-rule (`.kicad_dru`) output.
//!
//! This sink intentionally emits a conservative subset of KiCad custom rules.
//! It helps designers catch simple width, clearance, annular-ring, and edge
//! spacing issues earlier in KiCad without pretending to translate every
//! HyperDRC readiness check into KiCad's rule language.

use crate::config::EffectiveRules;

/// Render a KiCad custom-rule file from the resolved HyperDRC rule thresholds.
pub fn rules_to_kicad_dru(rules: &EffectiveRules) -> String {
    let mut text = String::new();
    text.push_str("(version 1)\n");
    text.push_str(
        "; Generated by HyperDRC. Review before merging with project-specific KiCad rules.\n",
    );
    text.push_str("; Units are millimeters.\n\n");
    push_rule(
        &mut text,
        "hyperdrc-copper-clearance",
        "Copper clearance exported from HyperDRC net_clearance.",
        "clearance",
        rules.net_clearance,
        "A.Type == 'track' || A.Type == 'via' || A.Type == 'pad'",
    );
    push_rule(
        &mut text,
        "hyperdrc-track-width",
        "Minimum copper width exported from HyperDRC min_width.",
        "track_width",
        rules.min_width,
        "A.Type == 'track'",
    );
    push_rule(
        &mut text,
        "hyperdrc-annular-ring",
        "Minimum annular ring exported from HyperDRC annular_ring.",
        "annular_width",
        rules.annular_ring,
        "A.Type == 'via' || A.Type == 'pad'",
    );
    push_rule(
        &mut text,
        "hyperdrc-silk-clearance",
        "Silkscreen clearance exported from HyperDRC clearance.",
        "silk_clearance",
        rules.clearance,
        "A.Layer == 'F.SilkS' || A.Layer == 'B.SilkS'",
    );
    push_rule(
        &mut text,
        "hyperdrc-board-edge-clearance",
        "Copper to board edge clearance exported from HyperDRC clearance.",
        "edge_clearance",
        rules.clearance,
        "A.Type == 'track' || A.Type == 'via' || A.Type == 'pad' || A.Type == 'zone'",
    );
    push_rule(
        &mut text,
        "hyperdrc-hole-clearance",
        "Hole to copper clearance exported from HyperDRC drill_clearance.",
        "hole_clearance",
        rules.drill_clearance,
        "A.Type == 'via' || A.Type == 'pad'",
    );
    text
}

/// Merge generated HyperDRC rules into a copy of an existing KiCad rule deck.
pub fn merge_rules_into_kicad_dru(existing: &str, rules: &EffectiveRules) -> String {
    let generated = strip_version_header(&rules_to_kicad_dru(rules));
    let retained = remove_hyperdrc_generated_rules(existing);
    let mut text = retained.trim_end().to_string();
    if !text.is_empty() {
        text.push_str("\n\n");
    }
    text.push_str("; BEGIN HYPERDRC GENERATED RULES\n");
    text.push_str(generated.trim());
    text.push('\n');
    text.push_str("; END HYPERDRC GENERATED RULES\n");
    text
}

fn strip_version_header(text: &str) -> String {
    text.lines()
        .skip_while(|line| line.trim_start().starts_with("(version "))
        .collect::<Vec<_>>()
        .join("\n")
}

fn remove_hyperdrc_generated_rules(existing: &str) -> String {
    if existing.contains("; BEGIN HYPERDRC GENERATED RULES") {
        let mut output = String::new();
        let mut skipping = false;
        for line in existing.lines() {
            if line.trim() == "; BEGIN HYPERDRC GENERATED RULES" {
                skipping = true;
                continue;
            }
            if skipping && line.trim() == "; END HYPERDRC GENERATED RULES" {
                skipping = false;
                continue;
            }
            if !skipping {
                output.push_str(line);
                output.push('\n');
            }
        }
        return output;
    }

    let mut output = String::new();
    let lines = existing.lines().collect::<Vec<_>>();
    let mut index = 0usize;
    while index < lines.len() {
        if lines[index].trim_start().starts_with("(rule \"hyperdrc-") {
            index = skip_list(lines.as_slice(), index);
        } else {
            output.push_str(lines[index]);
            output.push('\n');
            index += 1;
        }
    }
    output
}

fn skip_list(lines: &[&str], start: usize) -> usize {
    let mut depth = 0isize;
    let mut index = start;
    while index < lines.len() {
        depth += paren_delta(lines[index]);
        index += 1;
        if depth <= 0 {
            break;
        }
    }
    index
}

fn paren_delta(line: &str) -> isize {
    let mut delta = 0isize;
    let mut in_string = false;
    let mut escaped = false;
    for ch in line.chars() {
        if in_string {
            if escaped {
                escaped = false;
            } else if ch == '\\' {
                escaped = true;
            } else if ch == '"' {
                in_string = false;
            }
            continue;
        }
        match ch {
            '"' => in_string = true,
            '(' => delta += 1,
            ')' => delta -= 1,
            _ => {}
        }
    }
    delta
}

fn push_rule(
    text: &mut String,
    name: &str,
    note: &str,
    constraint: &str,
    min_mm: f64,
    condition: &str,
) {
    if !min_mm.is_finite() || min_mm <= 0.0 {
        return;
    }
    text.push_str(&format!(
        "(rule \"{name}\"\n  (severity warning)\n  (constraint {constraint} (min {}mm))\n  (condition \"{}\")\n  ; {note}\n)\n\n",
        format_mm(min_mm),
        escape_condition(condition)
    ));
}

fn format_mm(value: f64) -> String {
    let formatted = format!("{value:.6}");
    formatted
        .trim_end_matches('0')
        .trim_end_matches('.')
        .to_string()
}

fn escape_condition(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use crate::config::{RuleConfig, RuleOverrides, effective_rules};

    use super::{merge_rules_into_kicad_dru, rules_to_kicad_dru};

    #[test]
    fn kicad_dru_contains_core_constraints_with_mm_units() {
        let rules = effective_rules(&RuleConfig::default(), RuleOverrides::default());

        let dru = rules_to_kicad_dru(&rules);

        assert!(dru.starts_with("(version 1)"));
        assert!(dru.contains("(rule \"hyperdrc-copper-clearance\""));
        assert!(dru.contains("(constraint clearance (min 0.15mm))"));
        assert!(dru.contains("(constraint track_width (min 0.15mm))"));
        assert!(dru.contains("(constraint annular_width (min 0.15mm))"));
        assert!(dru.contains("(constraint hole_clearance (min 0.25mm))"));
        assert!(dru.contains("Generated by HyperDRC"));
    }

    #[test]
    fn kicad_dru_uses_overridden_thresholds() {
        let rules = effective_rules(
            &RuleConfig::default(),
            RuleOverrides {
                net_clearance: Some(0.1234567),
                min_width: Some(0.25),
                annular_ring: Some(0.2),
                drill_clearance: Some(0.35),
                ..RuleOverrides::default()
            },
        );

        let dru = rules_to_kicad_dru(&rules);

        assert!(dru.contains("(constraint clearance (min 0.123457mm))"));
        assert!(dru.contains("(constraint track_width (min 0.25mm))"));
        assert!(dru.contains("(constraint annular_width (min 0.2mm))"));
        assert!(dru.contains("(constraint hole_clearance (min 0.35mm))"));
    }

    #[test]
    fn kicad_dru_merges_generated_rules_without_mutating_custom_rules() {
        let rules = effective_rules(&RuleConfig::default(), RuleOverrides::default());
        let existing = "(version 1)\n(rule \"keep-this\"\n  (constraint clearance (min 0.5mm))\n)\n\n(rule \"hyperdrc-track-width\"\n  (constraint track_width (min 0.01mm))\n)\n";

        let merged = merge_rules_into_kicad_dru(existing, &rules);

        assert!(merged.contains("(version 1)"));
        assert!(merged.contains("(rule \"keep-this\""));
        assert!(merged.contains("; BEGIN HYPERDRC GENERATED RULES"));
        assert!(merged.contains("(rule \"hyperdrc-copper-clearance\""));
        assert_eq!(merged.matches("(rule \"hyperdrc-track-width\"").count(), 1);
        assert!(merged.contains("; END HYPERDRC GENERATED RULES"));
    }

    #[test]
    fn kicad_dru_replaces_previous_generated_block() {
        let rules = effective_rules(&RuleConfig::default(), RuleOverrides::default());
        let existing = "(version 1)\n; BEGIN HYPERDRC GENERATED RULES\n(rule \"hyperdrc-old\"\n)\n; END HYPERDRC GENERATED RULES\n(rule \"keep-this\"\n)\n";

        let merged = merge_rules_into_kicad_dru(existing, &rules);

        assert!(!merged.contains("hyperdrc-old"));
        assert!(merged.contains("(rule \"keep-this\""));
        assert_eq!(
            merged.matches("; BEGIN HYPERDRC GENERATED RULES").count(),
            1
        );
    }
}
